name: CI
on:
  push:
    branches:
      - master
      - mamoru
  pull_request:
    branches:
      - master
      - mamoru

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.20.8'
          check-latest: true
      - run: ./scripts/lint_allowed_geth_imports.sh
        shell: bash
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: .
          args: --timeout 3m
  test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.20.8'
        check-latest: true
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh
      shell: bash
    - run: ./scripts/coverage.sh
      shell: bash
  test-race:
    name: Golang Unit Tests Race Detection v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.20.8'
        check-latest: true
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh -race
      shell: bash
  avalanchego_e2e:
    name: AvalancheGo E2E Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.20.8'
        check-latest: true
    - name: Run e2e tests
      run: E2E_SERIAL=1 ./scripts/tests.e2e.sh
      shell: bash
